ecom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    # PAGE
    path('', frontpage, name='frontpage'),
    path('create-product-entry/', create_product_entry, name='create_product_entry'),
    path('signup/', signup, name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),

    # DATA
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),

    # AJAX
    path('create-ajax/', create_ajax, name='create_ajax'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField(blank=True, null=True)
    time = models.DateField(auto_now_add=True)
    stock = models.IntegerField()

    def __str__(self):
        return self.name

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductEntryForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "stock"]

    def clean_product_name(self):
        mood = self.cleaned_data["mood"]
        return strip_tags(mood)

    def clean_product_description(self):
        feelings = self.cleaned_data["feelings"]
        return strip_tags(feelings)

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.utils.html import strip_tags

import datetime
from main.forms import ProductEntryForm
from main.models import Product

# PAGE
@login_required(login_url='/login')
def frontpage(request):
    # products = Product.objects.filter(user=request.user)[0:4]
    last_login = request.COOKIES.get('last_login', 'Unknown')
    context = {
        # 'products': products,
        'last_login': last_login,
        'name': request.user.username,
    }
    return render(request, 'main.html', context)

@login_required(login_url='/login')
def create_product_entry(request):
    form = ProductEntryForm(request.POST or None)

    if form.is_valid() and request.method == 'POST':
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return redirect('main:frontpage')
    
    context = {'form': form}
    return render(request, 'product_entry.html', context)


# METHOD
def edit_product(request, id):
    product = Product.objects.get(pk = id)

    # Set product entry sebagai instance dari form
    form = ProductEntryForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:frontpage'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    product = Product.objects.get(pk = id)
    product.delete()
    return HttpResponseRedirect(reverse('main:frontpage'))


# DATA
def show_xml(request):
    data = Product.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


# AUTENTIFIKASI
def signup(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully')
            return redirect('main:login')
        
        else:
            print(form.errors)
            for field in form:
                for error in field.errors:
                    messages.error(request, error)
    
    context = {'form': form}
    return render(request, 'signup.html', context)

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:frontpage"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            messages.success(request, 'Logged in successfully')
            return response
        
        else:
            messages.error(request, 'Please enter a correct username and password.')

    else:
        form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    messages.success(request, 'Logged out successfully')
    return response


# AJAX
@csrf_exempt
@require_POST
def create_ajax(request):
    name = request.POST.get('name')
    price = request.POST.get('price')
    description = request.POST.get('description')
    stock = request.POST.get('stock')
    user = request.user

    if name != strip_tags(name) or description != strip_tags(description):
        return HttpResponse('HTML tags are not allowed', status=400)

    new_product = Product(
        name = name,
        price = price,
        description = description,
        stock = stock,
        user = user,
    )
    new_product.save()
    return HttpResponse(status=201)

main/templates/card_product.html
<div class="flex flex-col w-3/4 md:w-1/4 bg-white py-4 px-6 rounded-lg">
  <div class="flex justify-end space-x-1">
      <a href="{% url 'main:edit_product' product.pk %}">
          <div class="bg-white w-10 h-10 flex justify-center items-center rounded-lg">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
              </svg>
          </div>
      </a>

      <a href="{% url 'main:delete_product' product.pk %}">
          <div class="bg-red-400 hover:bg-red-500 w-10 h-10 flex justify-center items-center rounded-lg">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="white">
                  <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
              </svg>
          </div>
      </a>
  </div>

  <!-- <img src="" alt="" class="rounded-xl hover:shadow-lg"> -->
  <p class="pt-4 font-bold">{{ product.name }}</p>
  <p class="text-gray-400">Rp. {{ product.price }}</p>
  <p class="text-gray-400">{{ product.description }}</p>
</div>

main/templates/edit_product.html
<!-- ADD PRODUCT PAGE -->

{% extends 'base.html' %} 
{% block content %}
<section class="bg-blue-200 min-h-screen flex justify-center items-center pt-16 pb-32 md:py-16 md:pb-24">
    <div class="bg-gray-100 shadow-xl rounded-lg w-3/4 md:w-1/2 p-8">
        <h1 class="text-base md:text-xl font-bold mb-6 text-center text-gray-800">Edit Product Entry</h1>
        
        <form method="POST" class="space-y-6">
            {% csrf_token %}
            
            <!-- Render form fields -->
            <div class="block text-sm md:text-base font-semibold pr-3">
              <label for="id_name" class="">Name :</label>
              <div class="pb-3">
                  {{ form.name }}
              </div>

              <label for="id_price" class="">Price :</label>
              <div class="pb-3">
                  {{ form.price }}
              </div>

              <label for="id_description" class="">Description :</label>
              <div class="pb-3">
                  {{ form.description }}
              </div>

              <label for="id_stock" class="">Stock :</label>
              <div class="pb-3">
                  {{ form.stock }}
              </div>
            </div>
            
            <!-- Submit button -->
            <div class="flex justify-center">
              <button type="submit" class="text-xs md:text-base bg-blue-500 text-white font-semibold px-6 py-3 rounded-lg hover:bg-blue-600 transition duration-300">
                Edit Product
              </button>
            </div>
        </form>
    </div>
</section>

<style>
  textarea, input {
    resize: none;
    width: 100%;
    border: 1px solid #d1d5db; /* Border abu-abu */
    border-radius: 0.375rem; /* Rounded corners */
    padding-left: 10px; /* Menambahkan padding */
    padding-top: 2px;
    padding-bottom: 2px;
  }
  
</style>
{% endblock %}

main/templates/login.html
<!-- LOGIN PAGE -->

{% extends 'base.html' %}
{% block content %}
<section>
    <div class="flex justify-center bg-[#BFDBFE] pt-24 pb-36">
        <div class="w-3/4 md:w-1/2 px-12 md:px-16 bg-white p-12 shadow-xl rounded-xl">
            <div class="flex justify-center">
                <h1 class="mb-6 text-xl font-bold">Login</h1>
            </div>
    
            <form action="." method="post" class="space-y-3">
                {% csrf_token %}
                <div>
                    <label>Username</label>
                    <input type="text" name="username" class="w-full mt-2 py-2 md:py-4 px-6 bg-gray-100 border border-black rounded-xl text-sm md:text-base hover:border-[#3B3D77]">
                </div>

                <div>
                    <label>Password</label>
                    <input type="password" name="password" class="w-full mt-2 py-2 md:py-4 px-6 bg-gray-100 rounded-xl border border-black text-sm md:text-base hover:border-[#3B3D77]">
                </div>

                <!-- Print Error Gagal Login -->
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="py-1 md:py-3 px-6 bg-red-200 text-red-800 rounded-xl">
                                <p>{{ message }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
                    {% if messages %}
                        {{ messages.clear }}
                    {% endif %}
                {% endif %}

                <div>
                    <button class="py-2 md:py-4 px-5 md:px-6 rounded-xl text-white bg-[#3B3D77] hover:bg-black">
                        Submit
                    </button>
                </div>
            </form>

            <p class="py-4">Don't have an account? <a href="{% url 'main:signup' %}" class="text-blue-400">Sign Up</a></p>
        </div>

    </div>
</section>
{% endblock content %}

main/templates/main.html
<!-- PRODUCT SECTION -->

{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="flex justify-center items-center bg-[#BFDBFE]">
    <div class="flex flex-col items-center py-24 space-y-2">
        <div class="py-2 font-semibold">
            Welcome to Click Coffee
        </div>

        <!-- <a href="/">
            <button class="bg-indigo-700 py-2 px-4 text-white font-bold rounded-lg hover:bg-indigo-500 transition duration-300">Start Shopping</button>
        </a> -->

        <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-[#3B3D77] hover:bg-black text-white font-bold py-2 px-4 rounded-lg transition duration-300" onclick="showModal();">
            Add Product by AJAX
        </button>
      
    </div>
</section>

<section class="px-6 py-6 pb-[30rem]">
    <div id="product_cards"></div>
        
    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
    <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 border-b rounded-t">
        <h3 class="text-xl font-semibold text-gray-900 px-3">
            Add New Product
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
            <span class="sr-only">Close modal</span>
        </button>
        </div>
        <!-- Modal body -->
        <div class="px-6 py-4 space-y-6 form-style">
        <form id="productForm">
            <div class="mb-4">
                <label for="product" class="block text-sm font-medium text-gray-700">Name</label>
                <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-[#3B3D77]" placeholder="Enter product name" required>
            </div>

            <div class="mb-4">
                <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
                <input type="number" id="price" name="price" min="1" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-[#3B3D77]" required>
            </div>

            <div class="mb-4">
                <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
                <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-[#3B3D77]" placeholder="Describe your product" required></textarea>
            </div>

            <div class="mb-4">
                <label for="stock" class="block text-sm font-medium text-gray-700">Stock</label>
                <input type="number" id="stock" name="stock" min="1" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-[#3B3D77]" required>
            </div>
        </form>
        </div>
        <!-- Modal footer -->
        <div id="error-message" style="color: red; padding-left: 28px;"></div>

        <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
        <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
        <button type="submit" id="submitProduct" form="productForm" class="bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
        </div>
    </div>
    </div>


</section>

<!-- SCRIPT -->
<script>
    // Fungsi Refresh
    async function refreshProduct() {
        document.getElementById("product_cards").innerHTML = "";
        document.getElementById("product_cards").className = "";
        const product = await getProduct();
        let htmlString = "";
        let classNameString = "";
        console.log(product);

        if (product.length === 0) {
            classNameString = "flex flex-col items-center";
            htmlString += `
                <div class="flex flex-col items-center">
                    <img src="{% static 'image/meng.png' %}" alt="Sad face" class="w-52 h-32 mb-4"/>
                    <p>Mohon maaf. Belum ada coffee untuk saat ini.</p>
                </div>
            `;
        } else {
            classNameString = "flex flex-wrap gap-10 justify-center";
            product.forEach((item) => {
                htmlString += `
                <div class="flex flex-col w-3/4 md:w-1/4 bg-white py-4 px-6 rounded-lg">
                    <div class="flex justify-end space-x-1">
                        <a href="/edit-product/${item.pk}">
                            <div class="bg-[#3B3D77] w-10 h-10 flex justify-center items-center rounded-lg hover:bg-black transition duration-300">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="white">
                                    <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                                </svg>
                            </div>
                        </a>

                        <a href="/delete/${item.pk}">
                            <div class="bg-red-400 hover:bg-red-500 w-10 h-10 flex justify-center items-center rounded-lg">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="white">
                                    <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </a>
                    </div>

                    <p class="pt-4 font-bold">${item.fields.name}</p>
                    <p class="text-gray-400">Rp. ${item.fields.price}</p>
                    <p class="text-gray-400">${item.fields.description}</p>
                </div>
                `;
            });
        }

        document.getElementById("product_cards").className = classNameString;
        document.getElementById("product_cards").innerHTML = htmlString;
    
    }


    // MODAL
    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    function showModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modal.classList.remove('hidden'); 
        setTimeout(() => {
            modalContent.classList.remove('opacity-0', 'scale-95');
            modalContent.classList.add('opacity-100', 'scale-100');
        }, 50); 
    }

    function hideModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modalContent.classList.remove('opacity-100', 'scale-100');
        modalContent.classList.add('opacity-0', 'scale-95');

        setTimeout(() => {
            modal.classList.add('hidden');
        }, 150); 
    }

    document.getElementById("cancelButton").addEventListener("click", hideModal);
    document.getElementById("closeModalBtn").addEventListener("click", hideModal);


    // Fungsi Get Product
    async function getProduct() {
        return fetch("{% url 'main:show_json' %}").then((res) => res.json())
    }

    
    // Fungsi Add Product
    function addProduct() {
        event.preventDefault();  // Mencegah form submit standar
        document.getElementById("error-message").innerHTML = '';
        fetch("{% url 'main:create_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#productForm')),
            // headers: {
            //     'X-CSRFToken': '{{ csrf_token }}'  // Tidak menggunakan csrf_exempt
            // },
        })
        .then(response => {
            if (response.ok) {
                refreshProduct();  // Refresh daftar produk
                document.getElementById("productForm").reset();  // Reset form
                hideModal();  // Tutup modal
            } else {
                return response.text().then(text => {
                    document.getElementById("error-message").innerHTML = `<p>${text}</p>`;

                    setTimeout(() => {
                        document.getElementById("error-message").innerHTML = "";
                    }, 5000);
                });
            }
        })

        .catch(error => console.error('Fetch error:', error));
            return false;
    }
    
    refreshProduct();
    document.getElementById("productForm").addEventListener("submit", addProduct);

</script>
{% endblock content %}

main/templates/product_entry.html
<!-- ADD PRODUCT PAGE -->

{% extends 'base.html' %} 
{% block content %}
<section class="bg-[#BFDBFE] min-h-screen flex justify-center items-center pt-16 pb-32 md:py-16 md:pb-24">
    <div class="bg-white shadow-xl rounded-lg w-3/4 md:w-1/2 p-8">
        <h1 class="text-base md:text-xl font-bold mb-6 text-center text-gray-800">Add New Product</h1>
        
        <form method="POST" class="space-y-6">
            {% csrf_token %}
            
            <!-- Render form fields -->
            <div class="block text-sm md:text-base font-semibold pr-3">
              <label for="id_name" class="">Name :</label>
              <div class="pb-3">
                  {{ form.name }}
              </div>

              <label for="id_price" class="">Price :</label>
              <div class="pb-3">
                  {{ form.price }}
              </div>

              <label for="id_description" class="">Description :</label>
              <div class="pb-3">
                  {{ form.description }}
              </div>

              <label for="id_stock" class="">Stock :</label>
              <div class="pb-3">
                  {{ form.stock }}
              </div>
            </div>
            
            <!-- Submit button -->
            <div class="flex justify-center">
              <button class="text-xs md:text-base bg-[#BFDBFE] font-semibold px-6 py-3 rounded-lg hover:bg-blue-300 transition duration-300">
                  Add Product Entry
              </button>
            </div>
        </form>
    </div>
</section>

<style>
  textarea, input {
    resize: none;
    width: 100%;
    border: 1px solid #d1d5db; /* Border abu-abu */
    border-radius: 0.375rem; /* Rounded corners */
    padding-left: 10px; /* Menambahkan padding */
    padding-top: 4px;
    padding-bottom: 4px;
  }

  textarea:hover, input:hover {
    border-color: #3B3D77; /* Ubah border menjadi warna lain saat hover */
  }

</style>
{% endblock %}

templates/base.html
<!-- NAVBAR & FOOTER -->

{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>

    <nav class="border-b border-gray-300 bg-white">
        <div class="max-w-screen mx-auto py-4 px-6 md:px-12">
            <div class="flex justify-between">
                <a href="/" class="flex items-center font-bold">
                    Click Coffee
                </a>

                <!-- (Hamburger Icon) -->
                <div class="md:hidden flex">
                    <button id="mobileMenuButton" class="focus:outline-none">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7" />
                        </svg>
                    </button>
                </div>

                <!-- Desktop Menu -->
                <ul class="hidden md:flex items-center space-x-4">
                    <a href="/"><li>Shop</li></a>
                    <a href="/"><li>About</li></a>
                    <a href="/create-product-entry"><li>Add Product</li></a>
                </ul>

                <!-- Dropdown -->
                <div class="relative hidden md:inline-block">
                    <button id="dropdownButton" data-username="{{ current_user.username }}" class="inline-flex justify-center w-full rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50" aria-expanded="true" aria-haspopup="true">
                        {% if current_user %}
                            Hello, {{ current_user.username }}
                        {% else %}
                            Hello, Guest
                        {% endif %}

                        <svg class="-mr-1 ml-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 10.66l3.71-3.43a.75.75 0 011.06 1.06l-4.25 3.93a.75.75 0 01-1.06 0L5.21 8.29a.75.75 0 01.02-1.08z" clip-rule="evenodd" />
                        </svg>
                    </button>
            
                    <div id="dropdownMenu" class="hidden origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-gray-100 text-sm text-gray-700 px-4 py-2" role="menu" aria-orientation="vertical" aria-labelledby="dropdownButton">
                        <div class="py-1" role="none">
                            <a href="#" class="block hover:bg-gray-200" role="menuitem">Profile</a>
                            
                            <p class="py-2">Last Login : {{ last_login }}</p>
                            <a href="{% url 'main:logout' %}">
                                <button type="submit" class="w-full text-left bg-red-400 hover:bg-red-500 text-white text-center rounded-md" role="menuitem">
                                    Logout
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Mobile Menu -->
        <div id="mobileMenu" class="hidden md:hidden bg-gray-100 text-md text-gray-700 px-6 pt-4 pb-6">
            <ul class="flex flex-col items-center justify-center space-y-3 text-center">
                <li class="w-full">
                    <a href="/" class="block hover:bg-gray-200 rounded-lg py-2">Shop</a>
                </li>

                <li class="w-full">
                    <a href="/" class="block hover:bg-gray-200 rounded-lg py-2">About</a>
                </li>

                <li class="w-full">
                    <a href="/create-product-entry" class="block hover:bg-gray-200 rounded-lg py-2">Add Product</a>
                </li>

                <li class="w-full">
                    <a href="#" class="block hover:bg-gray-200 rounded-lg py-2">Profile</a>
                </li>    
                <p class="py-2">Last Login: {{ last_login }}</p>
                <li class="w-full">
                    <a href="{% url 'main:logout' %}" class="block bg-red-400 hover:bg-red-500 rounded-lg py-2 text-white">Logout</a>
                </li>
                
            </ul>
        </div>
        
    </nav>

    <body class="bg-gray-100">
        {% block content %} {% endblock content %}
    </body>

    <footer class="fixed bottom-0 left-0 right-0 md:flex justify-between bg-white px-6 py-3 text-xs md:text-base">
        <p>Nashwa Ghania (2306241770) PBP - F</p>
        <p>&copy;2024 Click Coffee. All rights reserved.</p>
    </footer>

    <!-- Scripts -->
    <script>
        var username = document.getElementById('dropdownButton').getAttribute('data-username'); // Mendapatkan username user yang sedang login
        var dropdownMenu = document.getElementById('dropdownMenu');
        var dropdownButton = document.getElementById('dropdownButton');
        var mobileMenu = document.getElementById('mobileMenu');
        var mobileMenuButton = document.getElementById('mobileMenuButton');
        
        document.getElementById('dropdownButton').addEventListener('click', function () {
            if (username){
                if (dropdownMenu.classList.contains('hidden')) {
                    dropdownMenu.classList.remove('hidden');
                } else {
                    dropdownMenu.classList.add('hidden');
                }
            }
        });

        document.getElementById('mobileMenuButton').addEventListener('click', function () {
            if (username){
                if (mobileMenu.classList.contains('hidden')) {
                    mobileMenu.classList.remove('hidden');
                } else {
                    mobileMenu.classList.add('hidden');
                }
            }
        });

        // Close Dropdown
        window.onclick = function(event) {
            if (!dropdownButton.contains(event.target)) {
                dropdownMenu.classList.add('hidden');
            }

            if (!mobileMenuButton.contains(event.target)) {
            mobileMenu.classList.add('hidden');
        }
        }
    </script>
</html>